# By Abdullah 

name: Docker Build and Push
on:
  push:
    branches:
      - main
jobs:
  update-docker-images:
    name: Update Docker Images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Build and Push Docker Image to GHCR
        run: |
          docker login --username A6du11ah --password ${{secrets.GITHUB_TOKEN}} ghcr.io
          docker build . --tag ghcr.io/tryos-labs/tryos_genai_lite_container:latest
          docker push ghcr.io/tryos-labs/tryos_genai_lite_container:latest
        shell: bash

      - name: Build and Push Docker Image to Docker Hub
        run: |
          docker login --username tryoslabs --password ${{secrets.DOCKER_HUB_TOKEN}} 
          docker build . --tag tryoslabs/tryos_genai_lite_container:latest
          docker push tryoslabs/tryos_genai_lite_container:latest
        shell: bash

      - name: Build and Push Docker Image to Amazon ECR
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region us-east-1
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/s3i6v6k1
          docker build -t tryoslabs/tryos_genai_lite_container .
          docker tag tryoslabs/tryos_genai_lite_container:latest public.ecr.aws/s3i6v6k1/tryoslabs/tryos_genai_lite_container:latest
          docker push public.ecr.aws/s3i6v6k1/tryoslabs/tryos_genai_lite_container:latest
        shell: bash
