# TryOS Labs

name: Notify Telegram
on: [push]
jobs:
  notify-telegram:
    name: Notify Telegram
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Notify Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} committed to the ${{ github.repository }} repository:
            ${{ github.event.commits[0].message }}

            Changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
